version: '3.4'

services:
  wlogsapi:
    image: ${DOCKER_REGISTRY-}wlogsapi
    build:
      context: .
      dockerfile: WlogsAPI/Dockerfile
    environment:
      api_key: "7bce170c1e89bd1aa12f675db8026563"
