FROM node:carbon
WORKDIR /usr/src/wlogs
COPY package*.json ./

RUN npm install
RUN npm run build

# note this one

#To bundle your app’s source code inside the Docker image, use the COPY instruction:
COPY . .
#Your app binds to port 3000 so you’ll use the EXPOSE instruction to have it mapped by the docker daemon:
EXPOSE 3000
CMD [“npm”, “start”]